server:
  port: 8071

spring:
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

logging:
  level:
    com:
      goaleaf:
        configserver: DEBUG