server:
  port: 8071

spring:
  application:
    name: "configserver"


  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Pplociennik/glf-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: pplociennik
          password: "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"

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com:
      goaleaf:
        configserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"